"""Removed old RSVP and AdditionalGuest models

Revision ID: 7ce3a24744d0
Revises: d5c28c8b46ac
Create Date: 2025-08-21 17:41:04.125658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ce3a24744d0'
down_revision = 'd5c28c8b46ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('additional_guest')
    op.drop_table('rsvp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rsvp',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('attending', sa.VARCHAR(length=10), nullable=False),
    sa.Column('plus_one', sa.INTEGER(), nullable=True),
    sa.Column('dietary_restrictions', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('additional_guest',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('guest_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('guest_dietary_restrictions', sa.TEXT(), nullable=True),
    sa.Column('rsvp_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['rsvp_id'], ['rsvp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
