"""Added Guest model for search-based RSVP

Revision ID: d5c28c8b46ac
Revises: bd200e1c0eb7
Create Date: 2025-08-20 22:26:41.452436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c28c8b46ac'
down_revision = 'bd200e1c0eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('party_id', sa.String(length=100), nullable=False),
    sa.Column('attending', sa.Boolean(), nullable=True),
    sa.Column('dietary_restrictions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest')
    # ### end Alembic commands ###
