"""Initial migration

Revision ID: d9e25b4859f2
Revises: 
Create Date: 2025-08-12 20:02:47.711459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e25b4859f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rsvp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('attending', sa.String(length=10), nullable=False),
    sa.Column('plus_one', sa.Integer(), nullable=True),
    sa.Column('dietary_restrictions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('additional_guest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_name', sa.String(length=100), nullable=False),
    sa.Column('guest_dietary_restrictions', sa.Text(), nullable=True),
    sa.Column('rsvp_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rsvp_id'], ['rsvp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('additional_guest')
    op.drop_table('rsvp')
    # ### end Alembic commands ###
